name: Linting, and formatting

on:
  pull_request:
    branches:
      - '**'

jobs:
  Continuous-Integration:
    name: "Perform linting and formatting"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3

      - name: "Install dependencies"
         run: npm install --legecy-peer-deps

      - name: "Run linting check"
        run: 'npm run lint:check'

      - name: "Run Formatting"
        run: 'npm run pretty:check'
        


